### ISSUE TITLE
Why is the M3U generator failing?

### ISSUE THREAD

**Issue by parthibratan** [benmoose39/YouTube_to_m3u#122]
as the title says...

**Comment by hpalavecino** [comment]
The problem seems to be here:

- "The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2"
- "The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v2"

But I don´t know how ti fix this. :(

**Comment by gyssi007** [comment]
I've been watching for 2 years and finally failed today

**Comment by parthibratan** [comment]
Yeah I didn't expect it would start failing now

**Comment by wizz666** [comment]
Any news to fix this?

**Comment by hpalavecino** [comment]
OK, It is working again... Thanks !!!

**Comment by parthibratan** [comment]
Thanks for fixing it!
